### ISSUE TITLE
A question about print Hartree.cube in AIMD for each steps

### ISSUE THREAD

**Issue by Tgernew** [robinzyb/BandAlignmentTutorial#1]
I am wondering that since the size of the Hartree.cube is so large , how can these data be stored?

**Comment by robinzyb** [comment]
You are right. The typical cube data for an interface system is larger than 10 MB for each snapshot. One can use the following two methods to reduce data size.
1. reduce the number of x y stride of cube file
2. archived with bqbtool

In first method,
One can properly reduce the number of x y stride through the setting of KEYWORD STRIDE in [cp2k manual](https://manual.cp2k.org/cp2k-2022_1-branch/CP2K_INPUT/FORCE_EVAL/DFT/PRINT/V_HARTREE_CUBE.html), since we only care about the Hartree potential along z dimension and average x y Hartree in a same plane. 

In second method,
If one would like to archive the cube files in case of future use or something, I recommend [bqbtool](https://brehm-research.de/bqb.php), it can efficiently compress the cube data into a small size file. The shortcoming is apparent, one has to uncompress the bqb file in order to access the cube data.

**Comment by Tgernew** [comment]
Many thanks to your reply@
